services:
  openldap:
    build:
      context: ./docker/openldap
      dockerfile: Dockerfile-tls
    image: ldap-openldap-tls:latest
    container_name: openldap
    hostname: ${LDAP_DOMAIN:-ldap.example.com}
    restart: unless-stopped
    ports:
      - "636:636"
      - "389:389"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORG:-Example Organization}
      - LDAP_DOMAIN=${LDAP_DOMAIN:-example.com}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_TLS=true
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_CRT_FILENAME=cert.pem
      - LDAP_TLS_KEY_FILENAME=privkey.pem
      - LDAP_TLS_CA_CRT_FILENAME=fullchain.pem
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_BACKEND=mdb
      - LDAP_LOG_LEVEL=256
      - CONTAINER_LOG_LEVEL=4
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
      - GUEST_USER_PASSWORD=${GUEST_USER_PASSWORD}
      - ADMIN_USER_PASSWORD=${ADMIN_USER_PASSWORD}
      - CONTRACTOR_PASSWORD=${CONTRACTOR_PASSWORD}
      - VIP_PASSWORD=${VIP_PASSWORD}
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - ldap-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=openldap"


volumes:
  ldap-data:
    driver: local
  ldap-config:
    driver: local

networks:
  ldap-network:
    driver: bridge
