version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: unless-stopped
    ports:
      - "636:636"
      - "389:389"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORG:-Example Organization}
      - LDAP_DOMAIN=${LDAP_DOMAIN:-example.com}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_TLS=true
      - LDAP_TLS_ENFORCE=true
      - LDAP_TLS_CRT_FILENAME=ldap-certs/cert.pem
      - LDAP_TLS_KEY_FILENAME=ldap-certs/privkey.pem
      - LDAP_TLS_CA_CRT_FILENAME=ldap-certs/fullchain.pem
      - LDAP_TLS_PROTOCOL_MIN=3.3
      - LDAP_TLS_CIPHER_SUITE=HIGH:!aNULL:!MD5
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_BACKEND=mdb
      - LDAP_LOG_LEVEL=256
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
      - GUEST_USER_PASSWORD=${GUEST_USER_PASSWORD}
      - ADMIN_USER_PASSWORD=${ADMIN_USER_PASSWORD}
      - CONTRACTOR_PASSWORD=${CONTRACTOR_PASSWORD}
      - VIP_PASSWORD=${VIP_PASSWORD}
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - certificates:/etc/letsencrypt:ro
      - certificates:/container/service/slapd/assets/certs:ro
      - ldap-health:/opt/ldap-health
      - ./ldifs:/ldifs:ro
      - ./config/openldap:/opt/ldap-config:ro
    networks:
      - ldap-network
    depends_on:
      - certbot
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=openldap"

  certbot:
    build:
      context: ./docker/certbot
      dockerfile: Dockerfile
    image: ldap-certbot:latest
    container_name: certbot
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - certificates:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - certbot-logs:/opt/certbot-logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOMAIN=${LDAP_DOMAIN}
      - EMAIL=${LETSENCRYPT_EMAIL}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - RENEWAL_INTERVAL=${RENEWAL_INTERVAL:-43200}
      - DRY_RUN=${DRY_RUN:-false}
      - STAGING=${STAGING:-false}
    networks:
      - ldap-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=certbot"

volumes:
  ldap-data:
    driver: local
  ldap-config:
    driver: local
  certificates:
    driver: local
  certbot-www:
    driver: local
  ldap-health:
    driver: local
  certbot-logs:
    driver: local

networks:
  ldap-network:
    driver: bridge
