version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - certificates:/etc/letsencrypt
    entrypoint: sh
    command: >
      -c 'certbot certonly --standalone --non-interactive --agree-tos
      --email $${EMAIL} --domains $${DOMAINS}
      $$([ "$${STAGING}" = "true" ] && echo "--staging")
      $$([ "$${DRY_RUN}" = "true" ] && echo "--dry-run") &&
      trap exit TERM; while :; do certbot renew --quiet; sleep 43200 & wait $$!; done'
    environment:
      - DOMAINS=${DOMAINS:-ldap.example.com,radius.example.com}
      - EMAIL=${LETSENCRYPT_EMAIL}
      - STAGING=${STAGING:-false}
      - DRY_RUN=${DRY_RUN:-false}

volumes:
  certificates:
    driver: local