FROM osixia/openldap:1.5.0
LABEL maintainer="LDAP Admin <admin@tsengsyu.com>"

# Add custom TLS certificates using the official recommended approach
# Certificates will be copied from certbot container during build
COPY certs/ /container/service/slapd/assets/certs/

# Add automated user initialization for test environment
# The osixia/openldap image runs scripts from /container/service/:service_name/startup
COPY bootstrap/init-users.sh /container/service/slapd/startup/99-init-users.sh
RUN chmod +x /container/service/slapd/startup/99-init-users.sh